### ISSUE TITLE
validation of postgres user

### ISSUE THREAD

**Issue by kurthaemmerle** [sassoftware/sas-wvda#2]
hi everyone, it seems that the script does not correctly valiadte the "postgres" user if this user is an domain user. Please see attached fiel "sas-wvda_check_result.txt.

Thanks in advance
Regards,
Kurt

[sas-wvda_check_result.txt](https://github.com/sassoftware/sas-wvda/files/2556846/sas-wvda_check_result.txt)

**Comment by kurthaemmerle** [comment]
Hi 
can you provide some status about the issue described?
Thanks in advance
Kurt

**Comment by kurthaemmerle** [comment]
sorry did use wrong buton :)

**Comment by KenRGahagan** [comment]
Hello Kurt,
Apologies for the delayed reply.  I confirm that the script as written will only validate a local account.  The official documentation does specify that the account may be local or domain thus this is a bug and needs to be fixed.  I will make every effort to provide a fix by 03Dec2018.

**Comment by kurthaemmerle** [comment]
Hi Ken

Many thanks for looking into this.

Mit freundlichen Grüssen / Best regards

Kurt Hämmerle
Senior Systems Engineer ▪ Pre-Sales Services DACH
Tel: +41 44 805 74 67 ▪ Mobile: +41 79 745 16 53 ▪ kurt.haemmerle@sas.com<mailto:kurt.haemmerle@sas.com>
SAS Institute AG ▪ Richtistrasse 11 ▪ CH-8304 Wallisellen
www.sas.com/ch<http://www.sas.com/ch>
SAS® … THE POWER TO KNOW®

Von: Ken Gahagan <notifications@github.com>
Gesendet: Donnerstag, 29. November 2018 01:30
An: sassoftware/sas-wvda <sas-wvda@noreply.github.com>
Cc: Kurt Hämmerle <kurt.haemmerle@sas.com>; State change <state_change@noreply.github.com>
Betreff: Re: [sassoftware/sas-wvda] validation of postgres user (#2)


EXTERNAL

Hello Kurt,
Apologies for the delayed reply. I confirm that the script as written will only validate a local account. The official documentation does specify that the account may be local or domain thus this is a bug and needs to be fixed. I will make every effort to provide a fix by 03Dec2018.

**Comment by cnance-SAS** [comment]
The latest commit allows the validation of both domain and local accounts for the Postgres User.

**Comment by Shanttanoo** [comment]
Hi, 

I tried using **wvda ver**. **1.1.09** for a Viya 3.5 deployment where the postgres account is a domain account. 
However, the WARNING message is still shown - inspite of the fact that the postgres account is created in Active Directory. 

Can anyone help in this please? 

Thanks,
Shanttanoo
